// Generated by CoffeeScript 1.4.0
(function() {

  window.NAN = {};

  window.NAN.a = 123;

  NAN.BackgroundBlock = (function() {

    function BackgroundBlock() {
      this.id = $.backgroundBlockId;
      $.backgroundBlockId += 1;
      this.x = (1.2 + Math.random()) * $("body").height();
      this.y = Math.random() * $("body").width();
      this.size = Math.random() * 30 + 20;
      $("body").append("<div class='background-block' id='background-block-" + this.id + "' style='width: " + this.size + "px; height: " + this.size + "px'> </div>");
      this.getElement().css("-webkit-transform", "rotateZ(" + (Math.random() * 360) + "deg)");
      this.getElement().css("background-color", "hsl(" + (Math.random() * 360) + ", 50%, 40%)");
      this.update();
    }

    BackgroundBlock.prototype.getElement = function() {
      return $("#background-block-" + this.id);
    };

    BackgroundBlock.prototype.update = function() {
      this.x -= 2;
      if (this.x < -100) {
        this.x = $("body").height();
      }
      this.getElement().css("left", "" + this.y + "px");
      this.getElement().css("top", "" + this.x + "px");
      return this.getElement().css("z-index", "-10000");
    };

    return BackgroundBlock;

  })();

  NAN.Background = (function() {

    function Background() {
      var i, _i;
      this.blocks = [];
      for (i = _i = 0; _i < 50; i = ++_i) {
        this.blocks.push(new NAN.BackgroundBlock);
      }
    }

    Background.prototype.update = function() {
      var block, _i, _len, _ref, _results;
      _ref = this.blocks;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        block = _ref[_i];
        _results.push(block.update());
      }
      return _results;
    };

    return Background;

  })();

}).call(this);
