// Generated by CoffeeScript 1.4.0
(function() {

  NAN.Score = (function() {

    function Score() {
      this.value = 0;
      this.displayedValue = 0;
      this.position = {
        x: 20,
        y: $("#container").width() / 2
      };
    }

    Score.prototype.addValue = function(points) {
      return this.value += points;
    };

    Score.prototype.update = function() {
      var delta;
      delta = (this.value - this.displayedValue) * 0.1;
      this.displayedValue += delta;
      return $(".score").html("" + (Math.floor(this.displayedValue + 0.3)));
    };

    return Score;

  })();

  NAN.NumberShow = (function() {

    function NumberShow(data) {
      var _this = this;
      this.getElementAjax().hide(0);
      this.totalFrames = 50;
      this.time = 0;
      this.finished = false;
      this.clicked = false;
      this.getElement().show();
      setStyleRuleValue(".number", "visibility", "hidden");
      this.getElement().animate({
        opacity: "0.70"
      }, 200);
      this.getElementNumber().html(data.n);
      this.getElementScore().html(data.score.toString() + " points");
      if (data.descriptions === null || data.descriptions === "") {
        data.descriptions = "平凡的数";
      } else {
        this.queryServer(data.n);
      }
      this.getElementDescriptions().html(data.descriptions);
      this.getElement().click(function() {
        return _this.onClick();
      });
      this.getElement().on("touchstart", function() {
        return _this.onClick();
      });
      this.getElement().on("touchmove", function() {
        return _this.onClick();
      });
      this.getElement().on("touchend", function() {
        return _this.onClick();
      });
    }

    NumberShow.prototype.queryServer = function(n) {
      var _this = this;
      queryNumber(-1);
      return queryNumber(n, function(text) {
        _this.getElementAjax().html("您第" + text + "个发现了这个数");
        return _this.getElementAjax().fadeIn(200);
      });
    };

    NumberShow.prototype.getElement = function() {
      return $("#number-show");
    };

    NumberShow.prototype.getElementNumber = function() {
      return $("#number-show-number");
    };

    NumberShow.prototype.getElementScore = function() {
      return $("#number-show-score");
    };

    NumberShow.prototype.getElementDescriptions = function() {
      return $("#number-show-descriptions");
    };

    NumberShow.prototype.getElementAjax = function() {
      return $("#number-show-ajax");
    };

    NumberShow.prototype.onClick = function() {
      var _this = this;
      if (this.clicked) {
        return;
      }
      this.clicked = true;
      console.log(this.finished);
      this.getElement().animate({
        opacity: "0.0"
      }, 200);
      setTimeout(function() {
        _this.finished = true;
        return _this.getElement().hide();
      }, 200);
      return setStyleRuleValue(".number", "visibility", "visible");
    };

    NumberShow.prototype.update = function() {
      var ratio;
      this.time += 1;
      return ratio = (1 + Math.cos(this.time / this.totalFrames * Math.PI)) / 2;
    };

    return NumberShow;

  })();

}).call(this);
