gl:
	g++ -o hello hello.cpp -I /Users/Iterator/homebrew/Cellar/glew/1.11.0/include -L /Users/Iterator/homebrew/Cellar/glew/1.11.0/lib -framework OpenGL -framework GLUT -lGLEW -Wnodeprecated-declarations
